# Generated by Django 5.0.4 on 2024-04-09 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='initiator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='convo_starter',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='convo_participant',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                to='chat.conversation'
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='message_sender',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
